# Generated by Django 4.2.23 on 2025-07-25 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('total_points', models.IntegerField(default=0)),
                ('full_name', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('show_vision_publicly', models.BooleanField(default=True)),
                ('show_task_publicly', models.BooleanField(default=True)),
                ('gmail_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('oauth_token', models.TextField(blank=True, null=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend_of', to='accounts.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='accounts.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='accounts.userprofile')),
            ],
        ),
    ]
