# Generated by Django 4.2.23 on 2025-08-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
