# Generated by Django 4.2.23 on 2026-01-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprofile_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_journal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weekly_points",
            field=models.IntegerField(default=0),
        ),
    ]
