# Generated by Django 4.2.23 on 2026-01-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_last_point_award_date'),
        ('accounts', '0007_add_privacy_fields'),
    ]

    operations = [
    ]
