# Generated by Django 4.2.23 on 2026-01-11 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20260111_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='show_vision_publicly',
        ),
    ]
