# Generated by Django 4.2.23 on 2026-01-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionboard', '0002_migrate_to_visionboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visioncomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this checkpoint'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='order',
            field=models.IntegerField(default=0, help_text='Order/position in the roadmap'),
        ),
        migrations.AlterField(
            model_name='visionboard',
            name='description',
            field=models.TextField(help_text='Detail about your vision'),
        ),
        migrations.AlterField(
            model_name='visionboard',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Make this vision board public or private'),
        ),
        migrations.AlterField(
            model_name='visionboard',
            name='points',
            field=models.IntegerField(default=20, help_text='Points awarded when achieved (minimum 20)'),
        ),
    ]
