# Generated by Django 4.2.23 on 2025-08-23 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-received_at']},
        ),
        migrations.RenameField(
            model_name='email',
            old_name='is_read',
            new_name='is_resolved',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='gmail_id',
            new_name='thread_id',
        ),
        migrations.RemoveField(
            model_name='email',
            name='replied',
        ),
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
        migrations.AddField(
            model_name='email',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='email',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='GmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_emails', models.IntegerField(default=0)),
                ('solved_emails', models.IntegerField(default=0)),
                ('pending_emails', models.IntegerField(default=0)),
                ('gmail_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='emails.gmailaccount')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='gmail_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.gmailaccount'),
        ),
    ]
