# Generated by Django 4.2.23 on 2025-10-28 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Journal entries'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('', 'Select Mood'), ('happy', '😊 Happy'), ('sad', '😢 Sad'), ('excited', '🤩 Excited'), ('angry', '😠 Angry'), ('peaceful', '😌 Peaceful'), ('anxious', '😰 Anxious'), ('tired', '😴 Tired'), ('productive', '💪 Productive')], max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
