# Generated by Django 4.2.23 on 2026-01-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_journalentry_options_journalentry_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="discovered_words",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of new words discovered"
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="points_earned",
            field=models.IntegerField(default=1),
        ),
    ]
