# Generated by Django 4.2.23 on 2026-01-09 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journal", "0003_journalentry_discovered_words_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="discovered_words",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="streak_points_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="word_points_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="points_earned",
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("journal_entry", "Journal Entry"),
                            ("word_discovery", "Word Discovery"),
                            ("streak_milestone", "Streak Milestone"),
                            ("task_completion", "Task Completion"),
                            ("vision_achieved", "Vision Achieved"),
                            ("journal_deleted", "Journal Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField()),
                (
                    "description",
                    models.CharField(
                        help_text="What earned/deducted these points", max_length=500
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the related object (journal, task, etc.)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveredWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                (
                    "meaning",
                    models.TextField(
                        blank=True, help_text="Word meaning from Gemini API"
                    ),
                ),
                (
                    "discovered_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_high_level",
                    models.BooleanField(
                        default=False, help_text="High-level word that earns +1 point"
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="journal.journalentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovered_words",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_date", "-created_at"],
                "unique_together": {("user", "word")},
            },
        ),
    ]
