# Generated by Django 4.2.23 on 2026-01-07 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("task_reminder", "Task Reminder"),
                    ("streak_warning", "Streak Warning"),
                    ("friend_request", "Friend Request"),
                    ("message", "New Message"),
                    ("achievement", "Achievement"),
                    ("points", "Points Milestone"),
                    ("system", "System"),
                ],
                default="system",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
