# Generated by Django 4.2.23 on 2026-01-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_add_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailytask",
            name="points",
            field=models.IntegerField(default=1),
        ),
    ]
