# Generated by Django 4.2.23 on 2026-01-11 01:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_enhance_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postshare',
            unique_together={('original_post', 'user')},
        ),
    ]
