# Generated by Django 4.2.23 on 2026-01-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#1e293b', max_length=7),
        ),
        migrations.AddField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
