# Generated by Django 4.2.23 on 2025-08-20 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important_emails_week', models.IntegerField(default=0)),
                ('important_emails_month', models.IntegerField(default=0)),
                ('unread_emails_count', models.IntegerField(default=0)),
                ('pending_tasks_count', models.IntegerField(default=0)),
                ('completed_tasks_week', models.IntegerField(default=0)),
                ('completed_tasks_month', models.IntegerField(default=0)),
                ('journal_entries_week', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
